### ISSUE TITLE
missing code for doing heterozygosity-filtering. 

### ISSUE THREAD

**Issue by timknut** [timknut/geno_imputation#23]
@Unoqualsiasi Steps 6 here: https://github.com/timknut/geno_imputation/blob/master/scripts/plink_workflow.Rmd 

It is unclear how you implemented the HET filter and at what threshold you set it? 
Can you please include how you made the file `hetero_remove` and the HEt threshold? This is the commit #16

**Comment by Unoqualsiasi** [comment]
Fixed

**Comment by argju** [comment]
Documented in hetero_geno.Rmd commits : 2ba77b29 & e940f395 
Closing #23
